src/Entity/Projet.php
<?php

namespace App\Entity;

use App\Repository\ProjetRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProjetRepository::class)
 */
class Projet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="float")
     */
    private $montant;

    /**
     * @ORM\Column(type="integer")
     */
    private $Part;

    /**
     * @ORM\ManyToOne(targetEntity=Soiree::class, inversedBy="idProjet")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idSoiree;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Apayer;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Arecevoir;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getPart(): ?int
    {
        return $this->Part;
    }

    public function setPart(int $Part): self
    {
        $this->Part = $Part;

        return $this;
    }

    public function getIdSoiree(): ?Soiree
    {
        return $this->idSoiree;
    }

    public function setIdSoiree(?Soiree $idSoiree): self
    {
        $this->idSoiree = $idSoiree;

        return $this;
    }

    public function getApayer(): ?float
    {
        return $this->Apayer;
    }

    public function setApayer(?float $Apayer): self
    {
        $this->Apayer = $Apayer;

        return $this;
    }

    public function getArecevoir(): ?float
    {
        return $this->Arecevoir;
    }

    public function setArecevoir(?float $Arecevoir): self
    {
        $this->Arecevoir = $Arecevoir;

        return $this;
    }

}

src/Form/PersonneType.php
<?php

namespace App\Form;

use App\Entity\Projet;
use App\Entity\Soiree;
use phpDocumentor\Reflection\Types\ClassString;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('Nom')
            ->add('Prenom')
            ->add('montant', MoneyType::class)
            ->add('Part', IntegerType::class, array('data' => 1))
            ->add("ok", SubmitType::class, ["label"=>"Enregistrer"])
        ;

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'idSoiree' => -1, // ne pas oublier de mettre une valeur par défaut
            'data_class' => Projet::class,
        ]);
    }

}

src/Controller/PersonneController.php
<?php

namespace App\Controller;

use App\Entity\Projet;
use App\Entity\Soiree;
use App\Form\PersonneSupprimerType;
use App\Form\PersonneType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PersonneController extends AbstractController
{
    /**
     * @Route("/personne/ajouter/{idSoiree}", name="ajouter_personne")
     */
    public function index(Soiree $idSoiree, Request $request)
    {
        $repo = $this->getDoctrine()->getRepository(Soiree::class);
        $soiree = $repo->find($idSoiree);

        $personne = new Projet();
        $form = $this->createForm(PersonneType::class, $personne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $personne->setIdSoiree($idSoiree);
            $em->persist($personne);
            $em->flush();
            unset($personne);
            unset($repo);
            unset($form);
            $personne = new Projet();
            $form = $this->createForm(PersonneType::class, $personne);
        }

        $personne=$soiree->getIdProjet();

        $repo = $this->getDoctrine()->getRepository(Projet::class);
        $total_montant = $repo->createQueryBuilder('test')
            ->select('SUM(test.montant) as total_montant')
            ->where('test.idSoiree = :id')
            ->setParameter('id', $idSoiree)
            ->getQuery()
            ->getSingleScalarResult();

        $total_part = $repo->createQueryBuilder('test')
            ->select('SUM(test.Part) as total_part')
            ->where('test.idSoiree = :id')
            ->setParameter('id', $idSoiree)
            ->getQuery()
            ->getSingleScalarResult();

        if ( $total_part != 0){
            $une_part = round($total_montant / $total_part, 2);
        }else{
            $une_part = '';
        }


        foreach ($personne as $p){
            if ($p->getMontant() > $une_part){
                $p->setArecevoir($p->getMontant() - ( $une_part * $p->getPart()));
            }elseif ($p->getMontant() < $une_part){
                $p->setApayer(( $une_part * $p->getPart() - $p->getMontant()));
            }
        }


        return $this->render('personne/index_ajouter.html.twig', [
            'soiree'=>$soiree,
            'personne'=>$personne,
            'total_montant' => $total_montant,
            'total_part' => $total_part,
            'une_part' => $une_part,
            "formulaire" => $form->createView()
        ]);
    }

    /**
     * @Route("/personne/modifier/{id}/{idSoiree}", name="modifier_personne")
     */

    public function modifier($id, Soiree $idSoiree, Request $request){

        $repo = $this->getDoctrine()->getRepository(Soiree::class);
        $soiree = $repo->find($idSoiree);

        $repo = $this->getDoctrine()->getRepository(Projet::class);
        $personne = $repo->find($id);



        $form = $this->createForm(PersonneType::class, $personne, [
            'idSoiree' => $idSoiree // valeur a envoyer
        ]);
        //gérer le retour du POST

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //récupérer l'entity manager (objet qui gère la connection a la BDD)
            $em = $this->getDoctrine()->getManager();

            //je dis au manager que je veux gardé l'objet en BDD
            $em->persist($personne);

            //je déclenche l'insert
            $em->flush();

            // je vais à la liste des catégories
            return $this->redirectToRoute("ajouter_personne", ["idSoiree"=>$personne->getIdSoiree()->getId()]);
        }

        return $this->render('personne/modifier.html.twig', [
            'formulaire' => $form->createView(),
            "personne"=>$personne,
            "soiree" => $soiree
        ]);
    }


    /**
     * @Route("/personne/supprimer/{id}/{idSoiree}", name="supprimer_personne")
     */

    public function supprimer($id, Soiree $idSoiree, Request $request){

        $repo = $this->getDoctrine()->getRepository(Soiree::class);
        $soiree = $repo->find($idSoiree);

        $repo = $this->getDoctrine()->getRepository(Projet::class);
        $personne = $repo->find($id);

        $form = $this->createForm(PersonneSupprimerType::class, $personne, [
            'idSoiree' => $idSoiree // valeur a envoyer
        ]);
        //gérer le retour du POST

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //récupérer l'entity manager (objet qui gère la connection a la BDD)
            $em = $this->getDoctrine()->getManager();

            //je dis au manager que je veux gardé l'objet en BDD
            $em->remove($personne);

            //je déclenche l'insert
            $em->flush();

            // je vais à la liste des catégories
            return $this->redirectToRoute("ajouter_personne", ["idSoiree"=>$personne->getIdSoiree()->getId()]);
        }

        return $this->render('personne/supprimer.html.twig', [
            'formulaire' => $form->createView(),
            "personne"=>$personne,
            "soiree" => $soiree
        ]);
    }
}

templates/personne/index_ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des personnes{% endblock %}

{% block body %}
    <h1>Ajouter une personne à la soirée : {{ soiree.Nom }}</h1>

    <table class="table table-dark">
        <tr>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Montant</th>
            <th>Part</th>
            <th>Montant à payer</th>
            <th>Montant à recevoir</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>


        {% for p in personne %}
            <tr>
                <td>{{ p.Nom }}</td>
                <td>{{ p.Prenom }}</td>
                <td>{{ p.Montant }} €</td>
                <td>{{ p.Part }}</td>
                <td class="text-danger"> {{ p.apayer }}
                    {% if  p.apayer  != null  %}
                        €
                    {% endif %}
                    </td>
                <td class="text-success">{{ p.arecevoir }}
                    {% if  p.arecevoir  != null  %}
                        €
                    {% endif %}
                </td>
                <td><a class="btn btn-warning" href="{{ path('modifier_personne', {"id":p.id, "idSoiree":soiree.id}) }}" >Modification</a></td>
                <td><a class="btn btn-danger" href="{{ path('supprimer_personne', {"id":p.id, "idSoiree":soiree.id}) }}" >Supprimer</a></td>
            </tr>
        {% endfor %}
    </table>
    <table class="table table-danger">
        <tr>
            <th>Total des montants</th>
            <th>Total des parts</th>
            <th>Le prix d'une part</th>
        </tr>
        <tr>
            <td>{{ total_montant }} €</td>
            <td>{{ total_part }}</td>
            <td>{{ une_part }} €</td>
        </tr>
    </table>

    {{ form(formulaire) }}

    <a class="btn btn-danger" href="{{ path("home_soiree") }}"> retour à la liste des soirées</a>

{% endblock %}

templates/personne/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'une personne{% endblock %}

{% block body %}
    <h1>Modification de la personne : {{ personne.Nom}} {{personne.Prenom}}

        Dans la soirée : {{ soiree.Nom }}</h1>

    {{ form(formulaire) }}

    <a class="btn btn-danger" href="{{ path("ajouter_personne", {"idSoiree":soiree.id}) }}"> retour aux détails de la soirée {{ soiree.Nom }}</a>

{% endblock %}

templates/personne/supprimer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supprimer une personne{% endblock %}

{% block body %}
    <h1>Supprimer {{ personne.Nom }} {{ personne.Prenom }}</h1>
    <h1>De la soirée : {{ soiree.Nom }}</h1>


    <h2>Etes vous sur de vouloir supprimer ? </h2>

    {{ form(formulaire) }}

    <a class="btn btn-danger" href="{{ path("ajouter_personne", {"idSoiree":soiree.id}) }}"> retour aux détails de la soirée {{ soiree.Nom }}</a>
{% endblock %}